tests: sfloat: convert to new test API
The sfloat test failed to link due to undefined reference to
ztest_skip_failed_assumption. Solve the issue by migrating to new test
API.

Signed-off-by: Tomasz Moń <tomasz.mon@nordicsemi.no>